messages:
  player-saved-notify:
  - '&7[i] Your items have been kept, because you had a keep inventory token in your inventory!'
  no-permission:
  - '&c[i] You do not have permission to use this command.'
item:
  material: GOLD_NUGGET
  name: '#6772a9Keep Inventory Token'
  lore:
  - '&7Keeps your inventory after death.'
  - '&7Must be inside your inventory.'
  - ' '
  - '#3a3277Item will be consumed on death.'
  modeldata: 0
